services:
    h2-database:
        image: oscarfonts/h2:latest
        container_name: h2-database
        ports:
            - "1521:1521"
            - "81:81"
        environment:
            H2_OPTIONS: "-inNotExists"
        volumes:
            - h2-data:C:\rad\h2-data

    spring-boot-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: spring-boot-app
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2-database:1521/test
            SPRING_DATASOURCE_USERNAME: sa
            SPRINT_DATASOURCE_PASSWORD: password
            SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
        depends_on:
            - h2-database

volumes:
    h2-data:
        driver: local